// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyTu2zhg2qpULwkvtKj__txLGJ6v4gl5g',
    appId: '1:589537709752:web:abbb40f34130ed53e16e4d',
    messagingSenderId: '589537709752',
    projectId: 'rally-app-6fb75',
    authDomain: 'rally-app-6fb75.firebaseapp.com',
    storageBucket: 'rally-app-6fb75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvownQ2tuE39njl0yJ3tM8du93sy1cSA',
    appId: '1:589537709752:android:85d598f18df839a1e16e4d',
    messagingSenderId: '589537709752',
    projectId: 'rally-app-6fb75',
    storageBucket: 'rally-app-6fb75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0p5py77J_k6p-Ae198i4Uc-N8BcMiG-A',
    appId: '1:589537709752:ios:b94ca954b5058ebae16e4d',
    messagingSenderId: '589537709752',
    projectId: 'rally-app-6fb75',
    storageBucket: 'rally-app-6fb75.firebasestorage.app',
    androidClientId: '589537709752-8v54d9fvmcp3ckrnvoks83gui1apb3lb.apps.googleusercontent.com',
    iosClientId: '589537709752-e52brf8h5o5v93v2rhlgv3g5a3sonmfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0p5py77J_k6p-Ae198i4Uc-N8BcMiG-A',
    appId: '1:589537709752:ios:b94ca954b5058ebae16e4d',
    messagingSenderId: '589537709752',
    projectId: 'rally-app-6fb75',
    storageBucket: 'rally-app-6fb75.firebasestorage.app',
    androidClientId: '589537709752-8v54d9fvmcp3ckrnvoks83gui1apb3lb.apps.googleusercontent.com',
    iosClientId: '589537709752-e52brf8h5o5v93v2rhlgv3g5a3sonmfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyTu2zhg2qpULwkvtKj__txLGJ6v4gl5g',
    appId: '1:589537709752:web:980ed2fe5d28a8cbe16e4d',
    messagingSenderId: '589537709752',
    projectId: 'rally-app-6fb75',
    authDomain: 'rally-app-6fb75.firebaseapp.com',
    storageBucket: 'rally-app-6fb75.firebasestorage.app',
  );
}
